# Generated by Django 4.1 on 2023-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
