# Generated by Django 4.1 on 2023-01-06 16:53

from django.db import migrations, models
import rental_app.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(default=0, validators=[rental_app.validations.validate_phone_number]),
        ),
    ]
