# Generated by Django 4.1 on 2023-01-06 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(default='', max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('production_year', models.IntegerField()),
                ('engine_size', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('description', models.CharField(default='', max_length=4000)),
                ('gearbox', models.CharField(choices=[('AUTO', 'automatic'), ('MANUAL', 'manual')], default='AUTO', max_length=20)),
                ('image', models.ImageField(default='', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Since when?')),
                ('date_to', models.DateField(verbose_name='Until when?')),
                ('additional_info', models.TextField(verbose_name='If you have any additional comments, please write us here.')),
                ('driver_license_length', models.IntegerField(verbose_name="How long have you held your driver's license")),
                ('driver_license_img', models.ImageField(upload_to='uploads/driver_licences', verbose_name="Send a scan of your driver's license.")),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rental_app.car', verbose_name='Which car you want to rent?')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
