# Generated by Django 4.1 on 2023-01-06 15:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_alter_reservation_date_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='driver_license_img',
            new_name='driver_licence_img',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='driver_license_length',
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver_licence_length',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name="How long have you held your driver's license (in years)"),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 1, 6)), django.core.validators.MinValueValidator(datetime.date(2023, 1, 6))], verbose_name='Since when?'),
        ),
    ]
