# Generated by Django 4.1 on 2023-01-06 15:36

import datetime
import django.core.validators
from django.db import migrations, models
import rental_app.validations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_rename_driver_license_img_reservation_driver_licence_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 1, 6)), django.core.validators.MinValueValidator(datetime.date(2023, 1, 7))], verbose_name='Until when?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='driver_licence_img',
            field=models.FileField(upload_to='uploads/driver_licences', validators=[rental_app.validations.validate_file_extension], verbose_name="Send a scan of your driver's license."),
        ),
    ]
