# Generated by Django 4.1 on 2023-01-06 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0005_alter_reservation_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(verbose_name='If you have any additional comments, please write us here about it.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='driver_licence_length',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name="How long have you held your driver's license? (in years)"),
        ),
    ]
